# Generated by Django 3.2.4 on 2021-11-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211105_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
    ]
