# Generated by Django 3.2.8 on 2021-12-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211106_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
