# Generated by Django 3.2.8 on 2021-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Формируется'), ('STP', 'Отправлен в обработку'), ('PRD', 'Обработан'), ('PD', 'Оплачен'), ('DN', 'Готов'), ('CN', 'Отменён')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
