# Generated by Django 3.2.8 on 2021-11-21 10:12

from django.db import migrations


def handle(apps, schema_editor):
    users = apps.get_model('authapp', 'ShopUser')
    profile = apps.get_model('authapp', 'ShopUserProfile')
    for user in users.objects.all():
        profile.objects.create(user=user)

class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0006_shopuserprofile'),
    ]

    operations = [
        migrations.RunPython(handle)
    ]
